# Generated by Django 4.2.2 on 2023-06-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='data_of_death',
            field=models.DateField(blank=True, help_text='Введите дату смерти', null=True, verbose_name='Дата смерти'),
        ),
        migrations.AlterField(
            model_name='author',
            name='data_of_birth',
            field=models.DateField(blank=True, help_text='Введите дату рождения', null=True, verbose_name='Дата рождения'),
        ),
    ]
